# Generated by Django 4.2.7 on 2024-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_contato_mostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
