# Generated by Django 4.2.7 on 2024-02-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_categ', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='cod_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contato.categoria'),
        ),
    ]
