# Generated by Django 4.2.7 on 2024-02-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_categoria_contato_cod_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cod_categ',
        ),
    ]
